// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AdvisoryNotificationsServiceLogging: AdvisoryNotificationsServiceStub {
    let inner: any AdvisoryNotificationsServiceStub
    let logger: Logger

    public init(_ inner: any AdvisoryNotificationsServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-advisorynotifications-v1"
      logger[metadataKey: "gcp.client.service"] = "advisorynotifications"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AdvisoryNotificationsService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listNotifications(
      request: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNotifications",
        action: {
          (r: ListNotificationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse
          in
          return try await self.inner.listNotifications(request: r, options: o)
        })
    }

    public func getNotification(
      request: GetNotificationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Notification {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNotification",
        action: {
          (r: GetNotificationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAdvisoryNotificationsV1.Notification
          in
          return try await self.inner.getNotification(request: r, options: o)
        })
    }

    public func getSettings(
      request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSettings",
        action: {
          (r: GetSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAdvisoryNotificationsV1.Settings
          in
          return try await self.inner.getSettings(request: r, options: o)
        })
    }

    public func updateSettings(
      request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSettings",
        action: {
          (r: UpdateSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAdvisoryNotificationsV1.Settings
          in
          return try await self.inner.updateSettings(request: r, options: o)
        })
    }
  }
}
