// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Service to manage Security and Privacy Notifications.
///
/// @Snippet(path: "AdvisoryNotificationsServiceQuickstart")
public final class AdvisoryNotificationsServiceClient: Clients.AdvisoryNotificationsServiceProtocol,
  Sendable
{
  let inner: any Clients.AdvisoryNotificationsServiceStub

  /// Creates a new `AdvisoryNotificationsServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AdvisoryNotificationsServiceStub =
      try Clients.AdvisoryNotificationsServiceTransport(options)
    inner = Clients.AdvisoryNotificationsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AdvisoryNotificationsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists notifications under a given parent.
  ///
  /// @Snippet(path: "AdvisoryNotificationsService_ListNotifications")
  public func listNotifications(
    request: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse {
    try await self.inner.listNotifications(request: request, options: options)
  }

  /// Lists notifications under a given parent.
  ///
  /// @Snippet(path: "AdvisoryNotificationsService_ListNotifications")
  public func listNotifications(
    byItem: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Notification, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listNotifications(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a notification.
  ///
  /// @Snippet(path: "AdvisoryNotificationsService_GetNotification")
  public func getNotification(
    request: GetNotificationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Notification {
    try await self.inner.getNotification(request: request, options: options)
  }

  /// Get notification settings.
  ///
  /// @Snippet(path: "AdvisoryNotificationsService_GetSettings")
  public func getSettings(
    request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
    try await self.inner.getSettings(request: request, options: options)
  }

  /// Update notification settings.
  ///
  /// @Snippet(path: "AdvisoryNotificationsService_UpdateSettings")
  public func updateSettings(
    request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
    try await self.inner.updateSettings(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AdvisoryNotificationsServiceClient`.
  ///
  /// To mock `AdvisoryNotificationsServiceClient` change your functions to receive
  /// `some AdvisoryNotificationsServiceProtocol` or `any AdvisoryNotificationsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AdvisoryNotificationsServiceProtocol {
    /// See `AdvisoryNotificationsServiceClient.listNotifications`.
    func listNotifications(request: ListNotificationsRequest) async throws
      -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse

    /// See `AdvisoryNotificationsServiceClient.listNotifications`.
    func listNotifications(
      byItem: ListNotificationsRequest
    ) throws -> any AsyncSequence<Notification, Swift.Error>

    /// See `AdvisoryNotificationsServiceClient.listNotifications`.
    func listNotifications(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Notification, Swift.Error>

    /// See `AdvisoryNotificationsServiceClient.getNotification`.
    func getNotification(request: GetNotificationRequest) async throws
      -> GoogleCloudAdvisoryNotificationsV1.Notification

    /// See `AdvisoryNotificationsServiceClient.getNotification`.
    func getNotification(
      name: Swift.String,
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Notification

    /// See `AdvisoryNotificationsServiceClient.getSettings`.
    func getSettings(request: GetSettingsRequest) async throws
      -> GoogleCloudAdvisoryNotificationsV1.Settings

    /// See `AdvisoryNotificationsServiceClient.getSettings`.
    func getSettings(
      name: Swift.String,
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings

    /// See `AdvisoryNotificationsServiceClient.updateSettings`.
    func updateSettings(request: UpdateSettingsRequest) async throws
      -> GoogleCloudAdvisoryNotificationsV1.Settings

    /// See `AdvisoryNotificationsServiceClient.updateSettings`.
    func updateSettings(
      settings: Settings?,
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings

    /// See `AdvisoryNotificationsServiceClient.listNotifications`.
    func listNotifications(
      request: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse

    /// See `AdvisoryNotificationsServiceClient.listNotifications`.
    func listNotifications(
      byItem: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Notification, Swift.Error>

    /// See `AdvisoryNotificationsServiceClient.getNotification`.
    func getNotification(
      request: GetNotificationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Notification

    /// See `AdvisoryNotificationsServiceClient.getSettings`.
    func getSettings(
      request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings

    /// See `AdvisoryNotificationsServiceClient.updateSettings`.
    func updateSettings(
      request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings
  }
}

// Default implementations
extension Clients.AdvisoryNotificationsServiceProtocol {
  public func listNotifications(request: ListNotificationsRequest) async throws
    -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse
  {
    try await self.listNotifications(request: request, options: .init())
  }

  public func listNotifications(
    request: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNotifications(
    byItem: ListNotificationsRequest
  ) throws -> any AsyncSequence<Notification, Swift.Error> {
    try self.listNotifications(byItem: byItem, options: .init())
  }

  public func listNotifications(
    byItem: ListNotificationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Notification, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAdvisoryNotificationsV1.ListNotificationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNotifications(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Notification, Swift.Error> {
    let request = ListNotificationsRequest().with {
      $0.parent = parent
    }
    return try self.listNotifications(byItem: request)
  }

  public func getNotification(request: GetNotificationRequest) async throws
    -> GoogleCloudAdvisoryNotificationsV1.Notification
  {
    try await self.getNotification(request: request, options: .init())
  }

  public func getNotification(
    request: GetNotificationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Notification {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getNotification(
    name: Swift.String,
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Notification {
    let request = GetNotificationRequest().with {
      $0.name = name
    }
    return try await self.getNotification(request: request)
  }

  public func getSettings(request: GetSettingsRequest) async throws
    -> GoogleCloudAdvisoryNotificationsV1.Settings
  {
    try await self.getSettings(request: request, options: .init())
  }

  public func getSettings(
    request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSettings(
    name: Swift.String,
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
    let request = GetSettingsRequest().with {
      $0.name = name
    }
    return try await self.getSettings(request: request)
  }

  public func updateSettings(request: UpdateSettingsRequest) async throws
    -> GoogleCloudAdvisoryNotificationsV1.Settings
  {
    try await self.updateSettings(request: request, options: .init())
  }

  public func updateSettings(
    request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSettings(
    settings: Settings?,
  ) async throws -> GoogleCloudAdvisoryNotificationsV1.Settings {
    let request = UpdateSettingsRequest().with {
      $0.settings = settings
    }
    return try await self.updateSettings(request: request)
  }
}
