// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for fetching all notifications for a given parent.
public struct ListNotificationsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of notifications.
  /// Must be of the form "organizations/{organization}/locations/{location}"
  /// or "projects/{project}/locations/{location}".
  public var parent: Swift.String = Swift.String()

  /// The maximum number of notifications to return. The service may return
  /// fewer than this value. If unspecified or equal to 0, at most 50
  /// notifications will be returned. The maximum value is 50; values above 50
  /// will be coerced to 50.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token returned from a previous request.
  /// When paginating, all other parameters provided in the request
  /// must match the call that returned the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Specifies which parts of the notification resource should be returned
  /// in the response.
  public var view: NotificationView = NotificationView()

  /// ISO code for requested localization language.  If unset, will be
  /// interpereted as "en". If the requested language is valid, but not supported
  /// for this notification, English will be returned with an "Not applicable"
  /// LocalizationState. If the ISO code is invalid (i.e. not a real language),
  /// this RPC will throw an error.
  public var languageCode: Swift.String = Swift.String()

  /// Initialize a new instance of `ListNotificationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListNotificationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.advisorynotifications.v1.ListNotificationsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
