// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Status of localized text.
public enum LocalizationState: Codable, Equatable, Sendable {
  /// Not used.
  case unspecified
  /// Localization is not applicable for requested language. This can happen
  /// when:
  /// - The requested language was not supported by Advisory Notifications at the
  /// time of localization (including notifications created before the
  /// localization feature was launched).
  /// - The requested language is English, so only the English text is returned.
  case notApplicable
  /// Localization for requested language is in progress, and not ready yet.
  case pending
  /// Localization for requested language is completed.
  case completed
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .notApplicable: return 1
    case .pending: return 2
    case .completed: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "LOCALIZATION_STATE_UNSPECIFIED"
    case .notApplicable: return "LOCALIZATION_STATE_NOT_APPLICABLE"
    case .pending: return "LOCALIZATION_STATE_PENDING"
    case .completed: return "LOCALIZATION_STATE_COMPLETED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LocalizationState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "LOCALIZATION_STATE_UNSPECIFIED": self = .unspecified
    case "LOCALIZATION_STATE_NOT_APPLICABLE": self = .notApplicable
    case "LOCALIZATION_STATE_PENDING": self = .pending
    case "LOCALIZATION_STATE_COMPLETED": self = .completed
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LocalizationState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .notApplicable
    case 2: self = .pending
    case 3: self = .completed
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .notApplicable: return try container.encode(1)
    case .pending: return try container.encode(2)
    case .completed: return try container.encode(3)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
