// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Type of notification
public enum NotificationType: Codable, Equatable, Sendable {
  /// Default type
  case unspecified
  /// Security and privacy advisory notifications
  case securityPrivacyAdvisory
  /// Sensitive action notifications
  case sensitiveActions
  /// General security MSA
  case securityMsa
  /// Threat horizons MSA
  case threatHorizons
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .securityPrivacyAdvisory: return 1
    case .sensitiveActions: return 2
    case .securityMsa: return 3
    case .threatHorizons: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "NOTIFICATION_TYPE_UNSPECIFIED"
    case .securityPrivacyAdvisory: return "NOTIFICATION_TYPE_SECURITY_PRIVACY_ADVISORY"
    case .sensitiveActions: return "NOTIFICATION_TYPE_SENSITIVE_ACTIONS"
    case .securityMsa: return "NOTIFICATION_TYPE_SECURITY_MSA"
    case .threatHorizons: return "NOTIFICATION_TYPE_THREAT_HORIZONS"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "NOTIFICATION_TYPE_UNSPECIFIED": self = .unspecified
    case "NOTIFICATION_TYPE_SECURITY_PRIVACY_ADVISORY": self = .securityPrivacyAdvisory
    case "NOTIFICATION_TYPE_SENSITIVE_ACTIONS": self = .sensitiveActions
    case "NOTIFICATION_TYPE_SECURITY_MSA": self = .securityMsa
    case "NOTIFICATION_TYPE_THREAT_HORIZONS": self = .threatHorizons
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .securityPrivacyAdvisory
    case 2: self = .sensitiveActions
    case 3: self = .securityMsa
    case 4: self = .threatHorizons
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .securityPrivacyAdvisory: return try container.encode(1)
    case .sensitiveActions: return try container.encode(2)
    case .securityMsa: return try container.encode(3)
    case .threatHorizons: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
