// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Settings for Advisory Notifications.
public struct Settings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the settings to retrieve.
  /// Format:
  /// organizations/{organization}/locations/{location}/settings or
  /// projects/{projects}/locations/{location}/settings.
  public var name: Swift.String = Swift.String()

  /// Required. Map of each notification type and its settings to get/set all
  /// settings at once. The server will validate the value for each notification
  /// type.
  public var notificationSettings: [Swift.String: NotificationSettings] = [:]

  /// Required. Fingerprint for optimistic concurrency returned in Get requests.
  /// Must be provided for Update requests. If the value provided does not match
  /// the value known to the server, ABORTED will be thrown, and the client
  /// should retry the read-modify-write cycle.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Settings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Settings().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.advisorynotifications.v1.Settings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
